### ISSUE TITLE
Remove hardcoded /secret path

### ISSUE THREAD

**Issue by SamyCoenen** [hashicorp/secrets-store-csi-driver-provider-vault#10]
You should be able to use secrets from kv engines that are mounted at different paths than /secret.

[Code reference](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/27973e8ebfd68387a75c8fa6645bcc893ae71a91/provider.go#L168)

Currently the documentation has a comment describing an example as the objectPath
>           objectPath: "/foo"                    # secret path in the Vault Key-Value store e.g. vault kv put secret/foo bar=hello

But as this diverges from the path you would normally use with the Vault API, it could be confusing.

**Comment by carnei-ro** [comment]
See my PR-8. https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/pull/8

**Comment by tomhjp** [comment]
Sorry for leaving this stale for a long time. As per the comment above, this was fixed in #8, and released in 0.0.5
