### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ritazh** [hashicorp/secrets-store-csi-driver-provider-vault#22]
Enable CI to create a kind cluster and run e2e tests for all PRs, similar to 
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/Makefile#L34-L55
And install the driver with helm then run the e2e tests for this provider, similar to this:
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/test/bats/azure.bats

**Comment by tomhjp** [comment]
Addressed in #60.
