### ISSUE TITLE
Unable to build cross-platform binary

### ISSUE THREAD

**Issue by burtlo** [hashicorp/secrets-store-csi-driver-provider-vault#33]
The `make build` step doesn't load the variables specified in the makefile as ENV variables for the make step itself. I worked around it by redefining the build step.

```shell
build: setup
	GOOS=$(GOOS) GOARCH=$(GOARCH) CGO_ENABLED=0 go build -a -ldflags $(LDFLAGS) -o _output/secrets-store-csi-driver-provider-vault_$(GOOS)_$(GOARCH)_$(IMAGE_VERSION) .
```

I don't spend a lot of time building Go code in Makefiles so I want to share that information but not sure about a PR.

**Comment by tomhjp** [comment]
Thanks for opening this, you're absolutely right - fixed on master now 👍
