### ISSUE TITLE
Remove automatic addition of data to the path with using KV2 secrets engines

### ISSUE THREAD

**Issue by burtlo** [hashicorp/secrets-store-csi-driver-provider-vault#35]
When defining the objectPath for the SecretProviderClass I expected that a KV2 secret path would need the entire path specified `/secret/data/database/config` versus what is supported `/secret/database/config`. I saw that the the provider detects the secret engine type and automatically adds `data`. This is inconsistent with the behavior of how the Vault Helm chart [annotations]( https://www.vaultproject.io/docs/platform/k8s/injector/#secrets-via-annotations) work.

**Comment by tomhjp** [comment]
Addressed in #63.
