### ISSUE TITLE
hashicorp/secrets-store-csi-driver-provider-vault:0.0.5 contains Mach-O binary

### ISSUE THREAD

**Issue by mitsutaka** [hashicorp/secrets-store-csi-driver-provider-vault#38]
I tried to use the latest version of the vault provider using https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/master/deployment/provider-vault-installer.yaml. However, `0.0.5` doesn't work with an error.

```console
time="2020-05-06T04:26:15Z" level=error msg="error invoking provider, err: fork/exec /etc/kubernetes/secrets-store-csi-providers/vault/provider-vault: exec format error, output:  for pod: d6a36b10-7155-46cb-aba6-fb40b9f4cfd8, ns: default"
```

0.0.5 includes Mach-O binary instead of ELF.

```console
$ docker run --rm -v /tmp:/tmp -e TARGET_DIR=/tmp hashicorp/secrets-store-csi-driver-provider-vault:0.0.5
install done, daemonset sleeping
...

$ file /tmp/vault/provider-vault
/tmp/vault/provider-vault: Mach-O 64-bit x86_64 executable
```

Since 0.0.4 is pushed with ELF binary. 0.0.5 should be the same format.

**Comment by kalafut** [comment]
0.0.5 has been repushed with the correct binary.

**Comment by mitsutaka** [comment]
confirmed. Thanks for fixing!
