### ISSUE TITLE
Helm chart for vault provider with deps

### ISSUE THREAD

**Issue by ritazh** [hashicorp/secrets-store-csi-driver-provider-vault#41]
Similar to https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/62

**Comment by hairmare** [comment]
I'm considering to contribute a chart based on the manifest provided in `deployment/provider-vault-installer.yaml`.

Other products have their own `-helm` repsitories (like [vault-helm](https://github.com/hashicorp/vault-helm)). Would it be ok to add the Chart directly to this repo like in the Azure Keyvault repo or does this need to be compatible with how HashiCorp delivers Helm charts for other products?

**Comment by tomhjp** [comment]
Hi @hairmare, thanks for your interest! We'll be adding a `csi` section to the existing chart in vault-helm when it's ready. There's actually a WIP branch for it at https://github.com/hashicorp/vault-helm/tree/add-csi-secrets-store-provider if you're interested. I'll be coming back around to that in the near future.

**Comment by tomhjp** [comment]
https://github.com/hashicorp/vault-helm/pull/461

**Comment by tomhjp** [comment]
PR above is merged to master, it should be getting released within the next week or two.
