### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pierreyves-lebrun** [hashicorp/secrets-store-csi-driver-provider-vault#46]
Is this project still alive?

I would love to use it in production but the lack of activity of this repo makes me wonder what the roadmap looks like.

**Comment by kalafut** [comment]
It's not dead 🙂, and we do have some near-term plans to dedicate more effort to this provider.

**Comment by pierreyves-lebrun** [comment]
That is great news, may I also ask what is missing for the project to be considered as production ready?

I would be more than happy to contribute!

**Comment by kalafut** [comment]
The initial version uses http call sand we'd prefer to switch to the Vault API package. There are a few other minor things too. Testing will be appreciated once those changes are in.  Thanks!
