### ISSUE TITLE
Feature Request: use namespace from requester

### ISSUE THREAD

**Issue by carnei-ro** [hashicorp/secrets-store-csi-driver-provider-vault#9]
I have scoped my Vault to the secrets path match the namespace in the Kubernetes.
I mean, I have a KV secret version 2 like **/sandbox/k8s_sres/my-app/db"**, than my namespace in Kubernetes is named "my-app". I forged a templated policy like this:
```
path "+/data/+/{{identity.entity.aliases.${ACCESSOR}.metadata.service_account_namespace}}*" {
  capabilities = ["read", "list"]
}
path "+/metadata/+/{{identity.entity.aliases.${ACCESSOR}.metadata.service_account_namespace}}*" {
  capabilities = ["read", "list"]
}
```
Then I have created a k8s auth backend role to bound to a specific service account name, but allowing all namespaces (I call it k8s_read_own_namespace_role)  

But all requests to login into Vault come from the namespace where **csi-secrets-store** is running, than I can not use my template policy to match the namespace metadata from the requester.

**Comment by tomhjp** [comment]
Thanks for raising this, it's a really good point to consider. I think fixing #16 should also fix this so I'll close as a dupe in favour of the broader feature - but I'll make sure I add an integration test that covers a scenario like this.
